---
- name: VLAN, Interface, SVI and Default Gateway Configuration Playbook
  hosts: switches
  gather_facts: True
  connection: network_cli
  vars:
    vlan_id: "{{ vlan_id }}"
    vlan_name: "{{ vlan_name }}"
    ansible_network_os: ios

  tasks:
    - name: LOADING - Collecting facts...
      cisco.ios.ios_facts:
        gather_subset:
          - config
          - interfaces

    - name: LOADING - Configuring user variables...
      set_fact:
        interface_list: "{{ interface_list | default('None') }}"
        default_gateway: "{{ default_gateway | default('') }}"
        svi_ip: "{{ svi_ip | default('') }}"
        svi_check: "{{ 'Vlan' ~ vlan_id not in ansible_net_interfaces }}"
        gtw_check: "{{ 'default-gateway' not in ansible_net_config }}"

    - name: LOADING - Checking if VLAN already exists...
      ios_command:
        commands:
          - "show vlan id {{ vlan_id }}"
      register: check_vlan
      ignore_errors: yes

    - name: STEP 1 - Configure VLAN
      cisco.ios.ios_vlans:
        config:
        - name: "{{ vlan_name }}"
          vlan_id: "{{ vlan_id }}"
          state: active
          shutdown: disabled
      when: check_vlan.failed

    - name: STEP 2.1 - Configure interfaces in access mode
      ios_l2_interfaces:
        config:
          - name: "{{ item[:-1] }}"
            access:
              vlan: "{{ vlan_id }}"
        state: merged
      loop: "{{ interface_list.split(',') | list }}"
      when: item[:-1] in ['a'] and interface_list != 'None'


    - name: STEP 2.2 - Configure interfaces in trunk mode
      ios_l2_interfaces:
        config:
          - name: "{{ item[:-1] }}"
            trunk:
              allowed_vlans: "{{ vlan_id }}"
              encapsulation: dot1q
        state: merged
      loop: "{{ interface_list.split(',') | list }}"
      when: item[-1] in ['t'] and interface_list != 'None'

    - name: STEP 3 - Configure SVI interface
      vars:
        svi_var: svi_check
      ios_l3_interfaces:
        config:
          - name: vlan " {{ vlan_id }}"
            ipv4:
            - address: "{{ svi_ip }}"
      when: "lookup('vars', svi_var) and svi_ip != ''"

    - name: STEP 4 - Configure default gateway
      vars:
        gtw_var: gtw_check
      ios_config:
        lines:
          - "ip routing"
          - "ip default-gateway {{ default_gateway }}"
      when: "lookup('vars', gtw_var) and default_gateway != ''"
