---
- name: Create a user on Cisco router
  hosts: switches
  gather_facts: True
  connection: network_cli
  vars:
    ansible_network_os: ios

  tasks:
    - name: LOADING - Collecting facts...
      cisco.ios.ios_facts:
        gather_subset:
          - config

    - name: LOADING - Processing variables...
      set_fact:
        username: "{{ username | default('') }}"
        password: "{{ password | default('12345') }}"

    - name: LOADING - Checking if user exists...
      set_fact:
        user_exists: "{{ username not in ansible_net_config }}"

    - name: STEP 1/1 Create user on Cisco router
      vars:
        user_var: user_exists
      cisco.ios.ios_user:
        name: "{{ username }}"
        privilege: 15
        state: present
        configured_password: "{{ password }}"
      when: "lookup('vars', user_var) and username != ''"
